# Generated by Django 4.2.7 on 2024-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delivery_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
