# Generated by Django 4.2.7 on 2024-12-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_is_processed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
